-- MySQL Script generated by MySQL Workbench
-- Sun Nov 11 14:53:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fog` DEFAULT CHARACTER SET utf8 ;
USE `fog` ;

-- -----------------------------------------------------
-- Table `fog`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`Customer` ;

CREATE TABLE IF NOT EXISTS `fog`.`Customer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fog`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`Order` ;

CREATE TABLE IF NOT EXISTS `fog`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `Height` INT NOT NULL,
  `Width` INT NOT NULL,
  `Length` INT NOT NULL,
  `Polls` INT NOT NULL,
  `Spears` INT NOT NULL,
  `customerID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `FK_Customer_idx` (`customerID` ASC),
  CONSTRAINT `FK_Customer`
    FOREIGN KEY (`customerID`)
    REFERENCES `fog`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
